Show file title in thumbnail popup
jneilliii/OctoPrint-UltimakerFormatPackage pull request #1
Opened 2019-08-23 09:55 UTC by fieldOfView

This PR changes the title of the popup to be the name of the UFP file. The popup is made a bit smaller, because the thumbnail files are always created at 300x300 pixels.

I also took the liberty to add a description and remove a todo here and there.

2019-08-23 11:52 UTC, jneilliii commented
Thanks. I was planning on doing the filename thing eventually. You saved me some work. I'll review you're changes today.

2019-08-23 13:34 UTC, jneilliii requested changes
Small typo @fieldOfView.

2019-08-23 13:34 UTC, jneilliii commented on octoprint_ultimakerformatpackage/static/js/UltimakerFormatPackage.js
> +		self,thumbnail_title = ko.observable('');
Shouldn't this be `self.thumbnail_title`?

2019-08-24 17:28 UTC, merged

2019-08-25 17:17 UTC, fieldOfView commented
Thanks for fixing my typo!